import type { Metadata } from "next";
import Link from "next/link";
import { requirePlatformAdmin } from "@/lib/auth/guards";
import { createClient } from "@/lib/supabase/server";
import BackLink from "@/components/back-link";
import ActionForm from "@/components/action-form";
import {
  setTrialRequestStatus,
  provisionFromTrialRequest,
} from "@/app/(app)/founder/actions";
import { tierLabel } from "@/lib/founder/format";
import {
  TRIAL_REQUEST_STATUSES,
  trialRequestStatusLabel,
  trialRequestStatusPillClass,
  safeMailto,
  safeTel,
  formatReceivedAt,
} from "@/lib/founder/trial-requests";
import {
  hoursWaiting,
  waitingLabel,
  waitingTone,
  alertDeliveryLabel,
} from "@/lib/founder/trial-alerts";
import {
  trialDomainFor,
  normalisePhone,
  sortMatches,
  type TrialMatch,
} from "@/lib/founder/trial-matching";

/**
 * Founder > Trial requests. Every "Start free trial" from the marketing site, newest
 * first, and the ONE place a trial is granted.
 *
 * WHY IT EXISTS. submitTrialRequest writes the row and emails the platform admin, and
 * until 0151 that email was the only place a lead was ever seen. One missed email and a
 * person who asked to buy the product heard nothing back. This screen makes the queue
 * a place rather than an inbox.
 *
 * IT NOW PROVISIONS, AND ONLY THE FOUNDER CAN (Phil, 2026-07-29, migration 0152). A
 * stranger still creates nothing. They ask, the request lands here carrying flags for
 * anything already seen, and one press builds the company, both branches, all five seed
 * catalogues and the Company Admin invite, starting the 14 day clock at the press rather
 * than at the request. There is no public provisioning route anywhere in the product.
 *
 * THE FLAGS ARE A READING AID, NOT THE RULE. Everything below is rendered so the founder
 * can decide; the rule that actually holds lives inside provision_company(), which
 * re-checks the same duplicates itself. A screen can be stale, opened twice, or bypassed
 * by a future caller. A function cannot.
 *
 * EVERYTHING ON IT WAS TYPED BY A STRANGER. Company name, contact name, message and the
 * rest arrive from an anonymous public form. They are rendered as ordinary React text,
 * which escapes by construction, and nothing here goes near dangerouslySetInnerHTML.
 * The only attributes built from stored values are the mailto: and tel: links, and each
 * is produced by a guard in lib/founder/trial-requests that returns null unless the
 * value plainly is an address or a phone number, in which case it is shown as plain
 * text instead.
 */

export const metadata: Metadata = { title: "Trial requests" };

type TrialRequestRow = {
  id: string;
  company_name: string;
  contact_name: string;
  email: string;
  phone: string | null;
  tier_interest: string | null;
  team_size: string | null;
  message: string | null;
  source: string;
  status: string;
  notes: string | null;
  status_changed_at: string | null;
  status_changed_by: string | null;
  created_at: string;
  company_id: string | null;
  /** Generated by public.company_name_key() in the database. Never recomputed here. */
  name_key: string | null;
  /* Whether the founder was actually TOLD about this one (0211). Never presented as
     delivered without a timestamp to prove it. */
  founder_alerted_at: string | null;
  founder_alert_error: string | null;
  founder_chased_at: string | null;
  founder_chase_count: number | null;
};

type CompanyRow = {
  id: string;
  name: string;
  name_key: string | null;
  trial_owner_email: string | null;
  trial_owner_domain: string | null;
  trial_ends_at: string | null;
};

/** Tiers a trial can start on. Black is granted by hand, never from a lead. */
const TRIAL_TIERS = ["business", "pro"] as const;

export default async function FounderTrialRequestsPage() {
  await requirePlatformAdmin();
  const supabase = await createClient();

  const [{ data }, { data: companyData }] = await Promise.all([
    supabase
      .from("trial_requests")
      .select(
        "id, company_name, contact_name, email, phone, tier_interest, team_size, message, source, status, notes, status_changed_at, status_changed_by, created_at, company_id, name_key, founder_alerted_at, founder_alert_error, founder_chased_at, founder_chase_count",
      )
      .order("created_at", { ascending: false })
      .limit(500),
    supabase
      .from("companies")
      .select("id, name, name_key, trial_owner_email, trial_owner_domain, trial_ends_at"),
  ]);

  const rows = (data ?? []) as TrialRequestRow[];
  const companies = (companyData ?? []) as CompanyRow[];

  // Name whoever last moved each request, in one lookup rather than one per row.
  const actorIds = [...new Set(rows.map((r) => r.status_changed_by).filter(Boolean))] as string[];
  const actorNames = new Map<string, string>();
  if (actorIds.length > 0) {
    const { data: actors } = await supabase
      .from("profiles")
      .select("id, full_name, email")
      .in("id", actorIds);
    for (const a of (actors ?? []) as Array<{ id: string; full_name: string | null; email: string | null }>) {
      actorNames.set(a.id, a.full_name || a.email || "Unknown");
    }
  }

  // Indexes built once for the whole page rather than once per request.
  const companyById = new Map(companies.map((c) => [c.id, c]));
  const companyByTrialEmail = new Map<string, CompanyRow>();
  const companyByTrialDomain = new Map<string, CompanyRow>();
  const companiesByNameKey = new Map<string, CompanyRow[]>();
  for (const c of companies) {
    if (c.trial_owner_email) companyByTrialEmail.set(c.trial_owner_email.toLowerCase(), c);
    if (c.trial_owner_domain) companyByTrialDomain.set(c.trial_owner_domain.toLowerCase(), c);
    if (c.name_key) {
      companiesByNameKey.set(c.name_key, [...(companiesByNameKey.get(c.name_key) ?? []), c]);
    }
  }

  /**
   * Everything we have seen before about one request. Silent when nothing matches, so a
   * flag on screen always means something. A name key of null (a company called nothing
   * but stripped words, such as "Care Ltd") never matches anything, which is why every
   * lookup below tests for null first rather than comparing two nulls.
   */
  function matchesFor(r: TrialRequestRow): TrialMatch[] {
    const found: TrialMatch[] = [];
    const email = r.email.trim().toLowerCase();
    const domain = trialDomainFor(email);
    const phone = normalisePhone(r.phone);

    const emailCompany = companyByTrialEmail.get(email);
    if (emailCompany && emailCompany.id !== r.company_id) {
      found.push({
        kind: "email",
        blocking: true,
        text: `This address already holds the trial on ${emailCompany.name}.`,
        href: `/founder/companies/${emailCompany.id}`,
      });
    }

    const domainCompany = domain ? companyByTrialDomain.get(domain) : undefined;
    if (domainCompany && domainCompany.id !== r.company_id) {
      found.push({
        kind: "domain",
        blocking: true,
        text: `Somebody at @${domain} already holds the trial on ${domainCompany.name}.`,
        href: `/founder/companies/${domainCompany.id}`,
      });
    }

    const sameEmail = rows.filter(
      (o) => o.id !== r.id && o.email.trim().toLowerCase() === email,
    );
    if (sameEmail.length > 0) {
      found.push({
        kind: "email",
        blocking: false,
        text: `This address has asked ${
          sameEmail.length === 1 ? "once before" : `${sameEmail.length} times before`
        }, most recently on ${formatReceivedAt(sameEmail[0].created_at)}.`,
      });
    }

    if (domain) {
      const sameDomain = rows.filter(
        (o) => o.id !== r.id && trialDomainFor(o.email) === domain,
      );
      if (sameDomain.length > 0) {
        found.push({
          kind: "domain",
          blocking: false,
          text: `${sameDomain.length === 1 ? "Another request" : `${sameDomain.length} other requests`} came from @${domain}, including ${sameDomain[0].company_name}.`,
        });
      }
    }

    if (r.name_key) {
      const nameCompanies = (companiesByNameKey.get(r.name_key) ?? []).filter(
        (c) => c.id !== r.company_id,
      );
      if (nameCompanies.length > 0) {
        found.push({
          kind: "name",
          blocking: false,
          text: `The name looks like an existing company: ${nameCompanies
            .slice(0, 3)
            .map((c) => c.name)
            .join(", ")}.`,
          href: `/founder/companies/${nameCompanies[0].id}`,
        });
      }
      const nameRequests = rows.filter((o) => o.id !== r.id && o.name_key === r.name_key);
      if (nameRequests.length > 0) {
        found.push({
          kind: "name",
          blocking: false,
          text: `The name looks like ${
            nameRequests.length === 1 ? "another request" : `${nameRequests.length} other requests`
          }: ${nameRequests
            .slice(0, 3)
            .map((o) => o.company_name)
            .join(", ")}.`,
        });
      }
    }

    if (phone) {
      const samePhone = rows.filter((o) => o.id !== r.id && normalisePhone(o.phone) === phone);
      if (samePhone.length > 0) {
        found.push({
          kind: "phone",
          blocking: false,
          text: `This phone number has been used on ${
            samePhone.length === 1 ? "another request" : `${samePhone.length} other requests`
          }: ${samePhone
            .slice(0, 3)
            .map((o) => o.company_name)
            .join(", ")}.`,
        });
      }
    }

    return sortMatches(found);
  }

  const newCount = rows.filter((r) => r.status === "new").length;

  return (
    <div className="w-full space-y-6">
      <div>
        <BackLink href="/founder" label="Back to Founder console" />
        <h1 className="page-title mt-1">Trial requests</h1>
        <p className="page-subtitle">
          Everyone who pressed Start free trial on the website, newest first. Nobody
          creates a company but you. Press Provision on a request and the whole company is
          built, seeded and invited, with the 14 day trial starting from that press.
        </p>
      </div>

      {rows.length > 0 ? (
        <p className="text-sm text-white/60">
          {rows.length} {rows.length === 1 ? "request" : "requests"} ·{" "}
          <span className={newCount > 0 ? "text-amber-300" : ""}>
            {newCount} new
          </span>
        </p>
      ) : null}

      {rows.length === 0 ? (
        <div className="glass-card px-6 py-12 text-center">
          <p className="text-sm text-white/60">
            No trial requests yet. Anyone who presses Start free trial on the website
            appears here straight away, and you still get the email.
          </p>
        </div>
      ) : (
        <div className="space-y-4">
          {rows.map((r) => {
            const mailto = safeMailto(r.email);
            const tel = safeTel(r.phone);
            const movedBy = r.status_changed_by ? actorNames.get(r.status_changed_by) : null;
            const matches = matchesFor(r);
            const blocked = matches.some((m) => m.blocking);
            const provisioned = r.company_id ? companyById.get(r.company_id) : undefined;
            const hours = hoursWaiting(r);
            const waiting = { label: waitingLabel(hours), tone: waitingTone(hours) };
            const delivery = alertDeliveryLabel(r);
            const defaultTier =
              r.tier_interest && (TRIAL_TIERS as readonly string[]).includes(r.tier_interest)
                ? r.tier_interest
                : "business";

            return (
              <section key={r.id} className="glass-card p-5">
                <div className="flex flex-wrap items-start justify-between gap-3">
                  <div>
                    <h2 className="text-base font-semibold text-white">{r.company_name}</h2>
                    <p className="text-sm text-white/60">
                      {r.contact_name} · received {formatReceivedAt(r.created_at)}
                    </p>
                  </div>
                  <div className="flex flex-wrap items-center gap-2">
                    {/* HOW LONG THEY HAVE BEEN WAITING, on the row itself. Two real companies
                        sat here for six days in August 2026 and nothing on this screen said
                        so — "received 27 Aug" reads the same on day one and day six. */}
                    {r.status === "new" ? (
                      <span
                        className={`pill ${
                          waiting.tone === "red"
                            ? "pill-red"
                            : waiting.tone === "amber"
                              ? "pill-amber"
                              : "pill-neutral"
                        }`}
                      >
                        {waiting.label}
                      </span>
                    ) : null}
                    <span className={`pill ${trialRequestStatusPillClass(r.status)}`}>
                      {trialRequestStatusLabel(r.status)}
                    </span>
                  </div>
                </div>

                {/* WAS HE EVER TOLD? Only ever claimed when there is a timestamp proving it. */}
                {!delivery.ok ? (
                  <p className="mt-2 text-xs text-amber-300">{delivery.text}</p>
                ) : null}

                <dl className="mt-4 grid gap-x-6 gap-y-2 text-sm sm:grid-cols-2">
                  <div>
                    <dt className="text-xs uppercase tracking-wide text-white/40">Email</dt>
                    <dd className="text-white/80">
                      {mailto ? (
                        <a href={mailto} className="underline decoration-white/30 hover:text-white">
                          {r.email}
                        </a>
                      ) : (
                        r.email
                      )}
                    </dd>
                  </div>
                  <div>
                    <dt className="text-xs uppercase tracking-wide text-white/40">Phone</dt>
                    <dd className="text-white/80">
                      {r.phone ? (
                        tel ? (
                          <a href={tel} className="underline decoration-white/30 hover:text-white">
                            {r.phone}
                          </a>
                        ) : (
                          r.phone
                        )
                      ) : (
                        <span className="text-white/40">Not given</span>
                      )}
                    </dd>
                  </div>
                  <div>
                    <dt className="text-xs uppercase tracking-wide text-white/40">Interested in</dt>
                    <dd className="text-white/80">
                      {r.tier_interest ? (
                        tierLabel(r.tier_interest)
                      ) : (
                        <span className="text-white/40">Not sure yet</span>
                      )}
                    </dd>
                  </div>
                  <div>
                    <dt className="text-xs uppercase tracking-wide text-white/40">Team size</dt>
                    <dd className="text-white/80">
                      {r.team_size ?? <span className="text-white/40">Not given</span>}
                    </dd>
                  </div>
                  <div>
                    <dt className="text-xs uppercase tracking-wide text-white/40">Came from</dt>
                    <dd className="text-white/80">{r.source}</dd>
                  </div>
                  <div>
                    <dt className="text-xs uppercase tracking-wide text-white/40">Last moved</dt>
                    <dd className="text-white/80">
                      {r.status_changed_at ? (
                        <>
                          {formatReceivedAt(r.status_changed_at)}
                          {movedBy ? ` by ${movedBy}` : ""}
                        </>
                      ) : (
                        <span className="text-white/40">Not worked yet</span>
                      )}
                    </dd>
                  </div>
                </dl>

                {r.message ? (
                  <div className="mt-4 rounded-lg border border-white/10 bg-white/[0.03] p-3">
                    <p className="text-xs uppercase tracking-wide text-white/40">
                      What they said
                    </p>
                    <p className="mt-1 whitespace-pre-wrap text-sm text-white/80">
                      {r.message}
                    </p>
                  </div>
                ) : null}

                {matches.length > 0 ? (
                  <div className="mt-4 rounded-lg border border-amber-400/30 bg-amber-400/[0.06] p-3">
                    <p className="text-xs uppercase tracking-wide text-amber-200/80">
                      Seen before
                    </p>
                    <ul className="mt-2 space-y-1.5">
                      {matches.map((m, i) => (
                        <li key={`${m.kind}-${i}`} className="flex flex-wrap items-center gap-2 text-sm">
                          <span className={`pill ${m.blocking ? "pill-red" : "pill-amber"}`}>
                            {m.blocking ? "Blocks" : "Check"}
                          </span>
                          <span className="text-white/80">{m.text}</span>
                          {m.href ? (
                            <Link
                              href={m.href}
                              className="text-xs underline decoration-white/30 hover:text-white"
                            >
                              Open it
                            </Link>
                          ) : null}
                        </li>
                      ))}
                    </ul>
                  </div>
                ) : null}

                {provisioned ? (
                  <div className="mt-4 border-t border-white/10 pt-4">
                    <p className="text-sm text-white/80">
                      Provisioned as{" "}
                      <Link
                        href={`/founder/companies/${provisioned.id}`}
                        className="underline decoration-white/30 hover:text-white"
                      >
                        {provisioned.name}
                      </Link>
                      {provisioned.trial_ends_at
                        ? `. The trial ends ${formatReceivedAt(provisioned.trial_ends_at)}.`
                        : "."}
                    </p>
                  </div>
                ) : (
                  <div className="mt-4 border-t border-white/10 pt-4">
                    <h3 className="text-sm font-semibold text-white">Provision the company</h3>
                    <p className="mt-1 text-xs text-white/50">
                      Builds the company, its Office and first Branch, and every starter
                      Form, check and training course, then invites {r.contact_name} at{" "}
                      {r.email} as the Company Admin. The trial starts now, not when they
                      asked.
                    </p>
                    {blocked ? (
                      <p className="mt-2 text-xs text-red-300">
                        This one is blocked because the address or the company domain has
                        already had a trial. Provisioning it anyway needs a reason, and
                        that reason is recorded in the audit log.
                      </p>
                    ) : null}

                    <ActionForm
                      action={provisionFromTrialRequest}
                      hidden={{ request_id: r.id }}
                      label={blocked ? "Provision anyway" : "Provision"}
                      savingLabel="Provisioning…"
                      savedLabel="Provisioned"
                      confirm={
                        blocked
                          ? "This address or company domain has already had a trial. Provision a second one anyway?"
                          : undefined
                      }
                      className="mt-3 space-y-3"
                    >
                      <div className="grid gap-3 sm:grid-cols-2">
                        <div>
                          <label htmlFor={`tier-${r.id}`} className="form-label">
                            Tier
                          </label>
                          <select id={`tier-${r.id}`} name="tier" defaultValue={defaultTier}>
                            {TRIAL_TIERS.map((t) => (
                              <option key={t} value={t}>
                                {tierLabel(t)}
                              </option>
                            ))}
                          </select>
                        </div>
                        <div>
                          <label htmlFor={`days-${r.id}`} className="form-label">
                            Trial days
                          </label>
                          <input
                            id={`days-${r.id}`}
                            name="trial_days"
                            type="number"
                            min={0}
                            max={90}
                            defaultValue={14}
                          />
                        </div>
                        <div>
                          <label htmlFor={`slug-${r.id}`} className="form-label">
                            Slug
                          </label>
                          <input
                            id={`slug-${r.id}`}
                            name="slug"
                            maxLength={60}
                            placeholder="Leave blank to use the company name"
                          />
                        </div>
                        <div>
                          <label htmlFor={`branch-${r.id}`} className="form-label">
                            First branch
                          </label>
                          <input
                            id={`branch-${r.id}`}
                            name="branch_name"
                            maxLength={80}
                            defaultValue="Main Branch"
                          />
                        </div>
                      </div>
                      {blocked ? (
                        <div>
                          <label htmlFor={`override-${r.id}`} className="form-label">
                            Why are you granting a second trial?
                          </label>
                          <input
                            id={`override-${r.id}`}
                            name="override_reason"
                            required
                            maxLength={500}
                            placeholder="A second service in the same group, a genuine new provider, and so on"
                          />
                        </div>
                      ) : null}
                    </ActionForm>
                  </div>
                )}

                <div className="mt-4 border-t border-white/10 pt-4">
                  <ActionForm
                    action={setTrialRequestStatus}
                    hidden={{ request_id: r.id }}
                    label="Save"
                    className="space-y-3"
                  >
                    <div>
                      <label htmlFor={`status-${r.id}`} className="form-label">
                        Status
                      </label>
                      <select id={`status-${r.id}`} name="status" defaultValue={r.status}>
                        {TRIAL_REQUEST_STATUSES.map((s) => (
                          <option key={s} value={s}>
                            {trialRequestStatusLabel(s)}
                          </option>
                        ))}
                      </select>
                    </div>
                    <div>
                      <label htmlFor={`notes-${r.id}`} className="form-label">
                        Notes
                      </label>
                      <textarea
                        id={`notes-${r.id}`}
                        name="notes"
                        rows={3}
                        maxLength={4000}
                        defaultValue={r.notes ?? ""}
                        placeholder="Who you spoke to, what was agreed, when to chase"
                      />
                    </div>
                  </ActionForm>
                </div>
              </section>
            );
          })}
        </div>
      )}
    </div>
  );
}
