"use server";

/**
 * Return to Work: drafting one with AI, and recording it as Evidence.
 *
 * The draft is a convenience, never a substitute for the conversation. It fills the
 * "Prepared for you" section from the absence record and the manager edits everything
 * before completing. Nothing is stored until they complete the form, so a draft they
 * dislike costs one AI credit and leaves no trace on the employee's file.
 *
 * THE QUESTIONS ARE DRAFTED, NOT FIXED (v3, migration 0147). Phil: "I wanted those
 * question fields generated by the ai when they press 'draft it for me' as not every
 * absence will be the same." So the model returns a small set of questions as STRICT
 * JSON, the dialog renders each as a real labelled control, and the answers are written
 * back into the single tailored_questions long_text as readable text. The questions
 * cannot be schema fields: Evidence pins a form_version id and the server validates
 * every answer against that stored schema, so a key invented this morning would be
 * dropped, and a version per absence would wreck the audit trail.
 *
 * ALL OF THEM, NOT JUST THE HEALTH ONES (v4, migration 0148). Phil: "'The conversation'
 * tile ... needs to also be ai and relevent to the absence." The fixed core v3 left
 * behind (fit to return, ongoing symptoms, work related, adjustments, support agreed) is
 * gone from the form, so the prompt below now REQUIRES the drafted set to cover that
 * ground. Referral and follow up date stay as real fields: they record what the manager
 * did, not what they asked.
 */

import { revalidatePath } from "next/cache";
import { requireCompany } from "@/lib/auth/guards";
import { createClient } from "@/lib/supabase/server";
import { writeAudit } from "@/lib/audit";
import { runAi } from "@/lib/ai/anthropic";
import { submitEvidence, type EvidenceFileInput } from "@/lib/evidence/submit";
import { getCompanyFormByKey } from "@/lib/people/data";
import { getRtwContext } from "./rtw";
import type { Answers } from "@/lib/form-schema";
import { stripJsonFence, toAiQuestions, type ActionState, type AiQuestion } from "@/lib/forms";

// v4: the model writes ALL of the questions. The guardrails below are unchanged from
// v1, v2 and v3 and must stay that way: never diagnose, never speculate about a medical
// cause, never suggest an outcome or disciplinary action.
//
// What changed in v4 (migration 0148) is the SCOPE. v3 told the model that fitness to
// return, work relatedness, adjustments and support were fixed fields and to never ask
// about them. Phil: "'The conversation' tile ... needs to also be ai and relevent to the
// absence." Those fields are gone, so the instruction is inverted: the drafted set MUST
// now cover that ground, in words written for this particular absence, and the cap rises
// to 8 (AI_QUESTION_LIMIT). Everything else, the strict JSON output and the prose
// fallback below, is untouched.
const RTW_SYSTEM = [
  "You are helping a UK care sector manager prepare for a Return to Work interview.",
  "Return to Work interviews are held after every absence. Your job is to prepare, not to decide.",
  "Write in plain British English. No dashes. Never diagnose, never speculate about a medical cause,",
  "and never suggest disciplinary action or an outcome: that is the manager's judgement after talking",
  "to the person. Be warm and practical. Assume the employee may be anxious about returning.",
  "Reply with STRICT JSON and nothing else: no markdown, no code fence, no words before or after it.",
  "The JSON is one object with exactly two keys.",
  '"summary": two or three sentences of factual context taken from the record.',
  '"questions": an array of 5 to 8 objects, each with "question" (one short question the manager',
  'should ask, written to be read aloud), "type" (exactly one of "text", "yes_no" or "choice") and,',
  'only when the type is "choice", "options" (an array of 2 to 4 short answers to choose from).',
  "The questions are the whole conversation, so the set MUST cover all four of these, each in at",
  "least one question and worded for this particular absence: whether they feel fit to return to",
  "their normal duties, whether any adjustments would help them come back, whether anything at work",
  "caused the absence or made it worse, and what support would help them now.",
  "Then use the remaining questions on what THIS absence calls for: the reason given, how long it",
  "lasted, and the pattern of their other absences on record. A back injury, a stomach bug and a run",
  "of single days do not deserve the same questions. Ask about a fit note, medication, appointments,",
  "a phased return or a pattern of absence only where this record makes it relevant.",
  "Ask one thing per question and never ask the same thing twice in different words.",
].join(" ");

// KEPT AS THE FALLBACK. If the model ignores the JSON instruction (or returns JSON we
// cannot make sense of) we read its reply as the old two heading prose instead of
// failing: the manager still gets a draft to edit, which is the whole point of the
// button, and the questions land in the tailored_questions box as plain text.
const ALSO_ASK_RE = /^\s*ALSO[ _]?ASK\s*:?\s*$/im;
const SUMMARY_RE = /^\s*SUMMARY\s*:?\s*$/im;

function splitDraft(text: string): { summary: string; alsoAsk: string } {
  const qIndex = text.search(ALSO_ASK_RE);
  const sIndex = text.search(SUMMARY_RE);
  if (qIndex === -1) return { summary: text.trim(), alsoAsk: "" };
  const summary = text
    .slice(sIndex === -1 ? 0 : sIndex, qIndex)
    .replace(SUMMARY_RE, "")
    .trim();
  const alsoAsk = text.slice(qIndex).replace(ALSO_ASK_RE, "").trim();
  return { summary, alsoAsk };
}

/**
 * Read the model's reply as { summary, questions }. Defensive on purpose: strip any
 * fence, parse in a try/catch, accept either the object we asked for or a bare array,
 * and drop any question whose shape is wrong (see toAiQuestions). questions is [] when
 * nothing survives, which tells the caller to fall back to prose. This NEVER throws.
 */
function readDraft(raw: string): { summary: string; questions: AiQuestion[] } {
  let parsed: unknown;
  try {
    parsed = JSON.parse(stripJsonFence(raw));
  } catch {
    return { summary: "", questions: [] };
  }
  if (Array.isArray(parsed)) return { summary: "", questions: toAiQuestions(parsed) };
  if (parsed && typeof parsed === "object") {
    const obj = parsed as Record<string, unknown>;
    const summary = typeof obj.summary === "string" ? obj.summary.trim() : "";
    return { summary, questions: toAiQuestions(obj.questions) };
  }
  return { summary: "", questions: [] };
}

/** Draft the Prepared for you section. Costs one AI credit; the credit is refunded by
 *  runAi if the call fails, so a failure never charges them. */
export async function draftReturnToWork(
  _prev: ActionState,
  formData: FormData,
): Promise<ActionState> {
  const { profile } = await requireCompany();
  if (!profile.company_id) return { error: "No company context." };
  const absenceId = String(formData.get("absence_event_id") ?? "");
  if (!absenceId) return { error: "Missing absence." };

  const ctx = await getRtwContext(absenceId);
  if (!ctx) return { error: "That absence could not be found." };

  const history = ctx.recent.length
    ? ctx.recent
        .map((r) => `- ${r.start_date} to ${r.end_date ?? "open"}, ${r.days ?? "unknown"} days, reason: ${r.reason ?? "not given"}`)
        .join("\n")
    : "- none recorded";

  const prompt = [
    `Employee: ${ctx.personName}`,
    `This absence: ${ctx.startDate} to ${ctx.endDate ?? "not ended"}${ctx.returnDate ? `, returned ${ctx.returnDate}` : ""}`,
    `Working days lost: ${ctx.days ?? "not recorded"}`,
    `Reason given: ${ctx.reason ?? "not recorded"}`,
    "",
    "Their other absences on record:",
    history,
  ].join("\n");

  const result = await runAi({
    companyId: profile.company_id,
    feature: "return_to_work",
    prompt,
    system: RTW_SYSTEM,
    maxTokens: 1600,
  });
  if ("error" in result) return { error: result.error };

  const { summary, questions } = readDraft(result.ok);
  if (questions.length > 0) {
    return {
      ok: "Drafted",
      // absence_summary is a real field key and is merged straight into the answers.
      // ai_questions is NOT a field: the dialog pulls it out, renders a control per
      // question, and writes the answers into tailored_questions on save.
      data: { absence_summary: summary, ai_questions: JSON.stringify(questions) },
    } as ActionState;
  }
  // Nothing usable came back as JSON. Fall back to the prose reading rather than
  // erroring: a draft the manager has to tidy up beats no draft at all, and both keys
  // below are real fields of the schema (0147, still there in v4 / 0148).
  const prose = splitDraft(result.ok);
  return {
    ok: "Drafted",
    data: {
      // A summary we PARSED beats one we guessed at: the model may have returned a
      // perfectly good summary alongside questions we could not use.
      absence_summary: summary || prose.summary,
      tailored_questions: prose.alsoAsk,
    },
  } as ActionState;
}

/** Record the completed interview as Evidence and close the Return to Work off. */
export async function recordReturnToWork(
  _prev: ActionState,
  formData: FormData,
): Promise<ActionState> {
  const { user, profile } = await requireCompany();
  if (!profile.company_id) return { error: "No company context." };
  const absenceId = String(formData.get("absence_event_id") ?? "");
  if (!absenceId) return { error: "Missing absence." };

  let answers: Answers;
  try {
    answers = JSON.parse(String(formData.get("answers") ?? "{}")) as Answers;
  } catch {
    return { error: "Could not read the form answers." };
  }

  const supabase = await createClient();
  const { data: absence } = await supabase
    .from("absence_events")
    .select("id, person_id, branch_id, rtw_evidence_id")
    .eq("id", absenceId)
    .maybeSingle();
  if (!absence) return { error: "That absence could not be found." };
  if (absence.rtw_evidence_id) {
    return { error: "A Return to Work has already been recorded for this absence." };
  }

  const form = await getCompanyFormByKey(profile.company_id, "return_to_work");
  if (!form) return { error: "The Return to Work form is not available for your company yet." };

  const files: EvidenceFileInput[] = [];
  for (const [key, value] of formData.entries()) {
    if (key.startsWith("file:") && value instanceof File && value.size > 0) {
      files.push({
        fieldKey: key.slice(5),
        kind: "upload",
        fileName: value.name,
        contentType: value.type || "application/octet-stream",
        bytes: Buffer.from(await value.arrayBuffer()),
      });
    }
  }

  const result = await submitEvidence({
    formVersionId: form.versionId,
    branchId: (absence.branch_id as string | null) ?? null,
    answers,
    files,
    recordType: "person",
    recordId: absence.person_id as string,
  });
  if (!result.ok) return { error: result.error };

  // Check the update landed: an RLS refusal returns no rows and no error, which would
  // otherwise leave the Return to Work showing as still outstanding forever.
  const { data: updated, error: updErr } = await supabase
    .from("absence_events")
    .update({ rtw_evidence_id: result.evidenceId })
    .eq("id", absenceId)
    .is("rtw_evidence_id", null)
    .select("id");
  if (updErr || !updated || updated.length === 0) {
    return { error: "The interview was saved as Evidence but the absence could not be updated." };
  }

  await writeAudit({
    companyId: profile.company_id,
    actorId: user.id,
    actorEmail: profile.email,
    actorRole: profile.role,
    action: "absence.return_to_work_recorded",
    entityType: "person",
    entityId: absence.person_id as string,
    summary: "Recorded a Return to Work interview",
    metadata: { absence_event_id: absenceId, evidence_id: result.evidenceId },
  });

  revalidatePath("/people/absence");
  revalidatePath(`/people/${absence.person_id}`);
  return { ok: "Recorded", redirectTo: `/people/absence` };
}
