-- 0021_supervision_drop_next_due_field
-- Remove the manual "Next supervision due" (next_supervision_due) field from the
-- supervision form (Phil, 2026-07-09): the next due date is auto-generated by the
-- recurrence engine on completion, so capturing it by hand is redundant. Removes it
-- from the master template and every supervision form version. Past evidence is
-- unaffected (each submission pins its own schema_snapshot). Applied to the
-- becarecompliant Supabase project ONLY (ref bgrtcvyjuwopunpnudeu).

update public.form_templates ft
set schema = jsonb_set(ft.schema, '{sections}', (
  select jsonb_agg(jsonb_set(sec, '{fields}', coalesce((
    select jsonb_agg(f order by ord)
    from jsonb_array_elements(sec->'fields') with ordinality e(f, ord)
    where f->>'key' <> 'next_supervision_due'
  ), '[]'::jsonb)) order by sord)
  from jsonb_array_elements(ft.schema->'sections') with ordinality s(sec, sord)
))
where ft.key = 'supervision';

update public.form_versions fv
set schema = jsonb_set(fv.schema, '{sections}', (
  select jsonb_agg(jsonb_set(sec, '{fields}', coalesce((
    select jsonb_agg(f order by ord)
    from jsonb_array_elements(sec->'fields') with ordinality e(f, ord)
    where f->>'key' <> 'next_supervision_due'
  ), '[]'::jsonb)) order by sord)
  from jsonb_array_elements(fv.schema->'sections') with ordinality s(sec, sord)
))
from public.forms f
where fv.form_id = f.id and f.key = 'supervision';
