-- Be Care Compliant — policies written or pasted in, not only uploaded.
--
-- Phil, 2026-07-26: "what about if people want to copy and paste their policy".
-- The original ruling (policies are UPLOADED DOCUMENTS) was about EVIDENCE, not
-- about the input method: an inspector wants the exact wording somebody signed,
-- years later. Pasted text keeps that promise as long as every version is frozen,
-- so a written policy still produces a real PDF per version, generated by us and
-- stored in the same private bucket. Nothing downstream changes: same versions,
-- same certificate, same exports, same RLS.
--
-- The text is kept as well as the PDF so the Team Member can read it as a proper
-- web page on a phone (reflowing, no pinch zoom) rather than squinting at a PDF.

alter table public.company_policies
  add column if not exists source text not null default 'upload',
  add column if not exists body text;

alter table public.company_policies
  drop constraint if exists company_policies_source_check;
alter table public.company_policies
  add constraint company_policies_source_check check (source in ('upload', 'text'));

-- The wording of THIS version, when the policy is a written one. Kept for good,
-- exactly like the file, because a signature names a version.
alter table public.company_policy_versions
  add column if not exists body text;

comment on column public.company_policies.source is
  'upload = a document the company uploaded; text = written or pasted into Be Care Compliant (we generate the PDF).';
comment on column public.company_policies.body is
  'The current wording, for source = text. Rendered as a web page for readers; the frozen PDF is the record.';
comment on column public.company_policy_versions.body is
  'The wording as signed at this version. Never edited in place.';
