-- 0147_return_to_work_v3
-- Phase 10 Additions (Phil, 2026-07-28, the same day 0145 shipped). Version 3 of the
-- Return to Work form. Phil, on seeing v2: "I wanted those question fields generated by
-- the ai when they press 'draft it for me' as not every absence will be the same."
--
-- He is right. v2 turned the questions into six FIXED fields (doctor seen, fit note,
-- medication and its conditional detail, outstanding appointments, anything at work
-- making it worse, what support would help). Those are the right questions for a back
-- injury and the wrong questions for a run of one day absences, and a fixed set asked
-- every time trains a manager to tick through them. The questions must be produced per
-- absence, from that absence, by the AI.
--
-- WHY THIS IS ONE long_text AND NOT A FIELD PER QUESTION. Evidence is immutable and pins
-- a form_version id, and lib/form-validate.ts validates every answer on the SERVER
-- against the STORED published schema, including single_select membership. So a question
-- the AI invented this morning cannot be an ordinary schema answer: the server has never
-- seen its key and would drop it. Minting a form version per absence would fix that and
-- wreck the audit trail, leaving thousands of one use versions and no way to say what
-- "the Return to Work form" is. So:
--   * the AI returns its questions as structured JSON to the browser only,
--   * the dialog renders each one as a real labelled control (text, Yes/No, or a choice)
--     so they are as clear to complete as fixed fields ever were,
--   * and the whole set is serialised into ONE long_text answer, tailored_questions, as
--     readable text: "Q: ..." then "A: ..." with a blank line between.
-- Readable text, not raw JSON, is the point. Evidence, the PDF renderer, the exports and
-- the on screen view already handle a long_text answer, so nothing downstream changes and
-- the record still reads like a record five years from now.
--
-- Changes from v2:
--  * REMOVED the six fixed question fields, and with them the whole "Health and fitness"
--    section. Also removed extra_questions ("Anything else worth asking"), which only
--    existed to let the AI ADD to the fixed set: the AI now writes the questions, so a
--    second box for the AI to write into is the same box twice.
--  * ADDED tailored_questions (long_text, "Questions asked and answers") to the Prepared
--    for you section.
--  * KEPT everything else v2 established: fit_to_return, work_related, the conditional
--    adjustments_needed, support_agreed, the conducted_by single_select whose options are
--    baked by public.rebake_form_field_options, completed_over_phone with the two
--    signature fields it switches between, interview_date and absence_summary.
--
-- Old evidence keeps the version it was completed against. Idempotent: the marker string
-- tailored_questions means a re-run does nothing.
-- Applied to the becarecompliant Supabase project ONLY (ref bgrtcvyjuwopunpnudeu).

do $$
declare
  v3 jsonb := $j${
    "schemaVersion": 1,
    "sections": [
      {
        "id": "section-1",
        "title": "Prepared for you",
        "description": "Drafted from the absence record. Read it, change anything that is not right, and delete what you did not use. Nothing here is sent anywhere until you complete the form.",
        "fields": [
          {"key": "absence_summary", "type": "long_text", "label": "Summary of the absence"},
          {"key": "tailored_questions", "type": "long_text", "label": "Questions asked and answers",
           "help": "Draft it for me writes a set of questions for this absence and turns them into boxes for you to fill in. Whatever you answer is recorded here, and you can type in it yourself."}
        ]
      },
      {
        "id": "section-2",
        "title": "The absence",
        "fields": [
          {"key": "absence_dates", "type": "short_text", "label": "Dates of absence"},
          {"key": "days_lost", "type": "short_text", "label": "Working days lost"},
          {"key": "reason_given", "type": "long_text", "label": "Reason given for the absence"}
        ]
      },
      {
        "id": "section-3",
        "title": "The conversation",
        "fields": [
          {"key": "fit_to_return", "type": "single_select", "label": "Fit to return to their normal duties",
           "required": true,
           "options": [
             {"label": "Yes", "value": "Yes"},
             {"label": "Yes, with adjustments", "value": "Yes, with adjustments"},
             {"label": "No", "value": "No"}
           ]},
          {"key": "ongoing_symptoms", "type": "long_text", "label": "Any ongoing symptoms or treatment"},
          {"key": "work_related", "type": "single_select", "label": "Was the absence work related",
           "options": [
             {"label": "No", "value": "No"},
             {"label": "Yes", "value": "Yes"},
             {"label": "Partly", "value": "Partly"}
           ]},
          {"key": "adjustments_needed", "type": "long_text", "label": "Adjustments needed on their return",
           "visibleWhen": {"field": "fit_to_return", "in": ["Yes, with adjustments", "No"]}}
        ]
      },
      {
        "id": "section-4",
        "title": "Support and next steps",
        "fields": [
          {"key": "support_agreed", "type": "long_text", "label": "Support agreed"},
          {"key": "referral", "type": "single_select", "label": "Referral made",
           "options": [
             {"label": "None", "value": "None"},
             {"label": "Occupational health", "value": "Occupational health"},
             {"label": "HR", "value": "HR"},
             {"label": "Their GP", "value": "Their GP"}
           ]},
          {"key": "follow_up_date", "type": "date", "label": "Follow up date"}
        ]
      },
      {
        "id": "section-5",
        "title": "Confirmation",
        "fields": [
          {"key": "employee_comments", "type": "long_text", "label": "Employee comments"},
          {"key": "conducted_by", "type": "single_select", "label": "Interview conducted by",
           "help": "Your staff list. Ask an administrator to add anyone missing.",
           "options": []},
          {"key": "interview_date", "type": "date", "label": "Date of the interview", "required": true},
          {"key": "completed_over_phone", "type": "checkbox",
           "label": "This interview was completed over the phone",
           "help": "Tick this and the interviewer signs instead of the employee."},
          {"key": "employee_signature", "type": "signature", "label": "Employee signature",
           "visibleWhen": {"field": "completed_over_phone", "in": ["false"]}},
          {"key": "interviewer_signature", "type": "signature",
           "label": "Interviewer signature confirming a conversation held over the phone",
           "help": "The employee is not present to sign, so you sign to confirm the conversation took place and this record is accurate.",
           "visibleWhen": {"field": "completed_over_phone", "in": ["true"]}}
        ]
      }
    ]
  }$j$::jsonb;
  f record;
  c record;
begin
  update public.form_templates
  set schema = v3, version = version + 1, updated_at = now()
  where key = 'return_to_work';

  for f in
    select fo.id
    from public.forms fo
    where fo.key = 'return_to_work'
      and not coalesce((
        select fv.schema::text like '%tailored_questions%'
        from public.form_versions fv
        where fv.form_id = fo.id and fv.status = 'published'
        order by fv.version desc limit 1
      ), false)
  loop
    insert into public.form_versions (form_id, version, schema, status)
    select f.id, coalesce(max(fv.version), 0) + 1, v3, 'published'
    from public.form_versions fv
    where fv.form_id = f.id;
  end loop;

  -- conducted_by ships with no options, exactly as in 0145, so the brand new version
  -- needs the company staff list baking into it. Without this the dropdown is empty and
  -- server side validation would reject any answer.
  for c in select id from public.companies loop
    perform public.rebake_form_field_options(c.id);
  end loop;
end $$;
